"""
End-to-end evaluation of the alerting pipeline.

Experiments (all regenerated by `python -m src.evaluate`):

  1. Zone classifier  - accuracy / per-class P-R-F1 on (a) a held-out uniform
                        sample of the region and (b) the synthetic trajectory set.
  2. One-step forecast - MAE / RMSE / ADE for LSTM, ConstVel, Kalman, scored
                        ONLY on trips with split == 'test' in data/vessel_data.csv.
  3. Horizon sweep    - for H in HORIZONS, each predictive policy, and each alert
                        predicate:
                          * Advance Warning Time on N_FORCED forced-crossing trips
                          * False-alert rate on N_NEAR near-miss trips that never
                            enter the DANGER zone (so any Danger alert is false)
                        Predicates:
                          'buffer'   - fire if any projected fix is on the SL side
                                       OR inside the 2 km DANGER buffer (what the
                                       dashboard ships)
                          'crossing' - fire only if a projected fix is on the SL
                                       side (a predicted crossing)
                        The reactive geofence is H-independent and is scored once.
                        Also checks eq. (1): AWT(pi_H) ~= H + AWT(reactive) for the
                        buffer predicate, and AWT ~= H for the crossing predicate.
  4. Latency          - per-tick wall-clock for the full single-vessel alerting
                        step (zone predict + 1-step + H-step rollout + predicate),
                        using the same un-batched call path as app.py.
  5. Model size       - trainable parameter count of the LSTM.

Trip sets are generated once with fixed seeds and shared across every policy,
horizon and predicate, so comparisons are paired.  One rollout of max(HORIZONS)
steps per tick serves every shorter horizon (a recursive rollout's first H steps
are identical regardless of the total length) and both predicates; LSTM
rollouts are batched across trips.

Outputs:
    results/awt.csv         one row per (policy, predicate, H, forced trip)
    results/far_sweep.csv   one row per (policy, predicate, H, near-miss trip)
    results/summary.json    everything the paper cites
"""

import json
import os
import random
import time

import numpy as np
import pandas as pd
from shapely.geometry import LineString, Point
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    precision_recall_fscore_support,
    roc_auc_score,
)

from src.baselines import (
    ConstantVelocityForecaster,
    KalmanForecaster,
    ReactiveGeofence,
)
from src.config import (
    CAUTION_DIST_KM,
    DANGER_DIST_KM,
    FORECAST_HORIZON,
    IMBL_POINTS,
    LSTM_LOOKBACK,
)
from src.data_generator import (
    generate_near_miss_trajectory,
    generate_trajectory,
    load_real_seed_data,
)
from src.geometry import distance_from_polyline, is_sri_lankan_side
from src.models import TrajectoryForecaster, ZoneClassifier
from src.train_model import build_classifier_training_set


N_FORCED = 50            # forced-crossing trips (AWT)
N_NEAR = 50              # near-miss, non-crossing trips (false-alert rate)
TRIP_LEN = 150           # ticks per forced trip
NEAR_LEN = 220           # ticks per near-miss trip (approach + trawl + return to port)
HORIZONS = [5, 10, 15, 20]
H_MAX = max(HORIZONS)
PREDICATES = ["buffer", "crossing"]
POST_CROSS_TICKS = 5     # forced trips are cut this many ticks after crossing
SEED_FORCED = 20260811
SEED_NEAR = 20260812
LATENCY_TICKS = 1000

PREDICTIVE = ["LSTM", "ConstVel", "Kalman"]


# --------------------------------------------------------------------------- #
# Geometry (cached segments; same maths as src/geometry.py)
# --------------------------------------------------------------------------- #
_SEGS = [LineString([(IMBL_POINTS[i][1], IMBL_POINTS[i][0]),
                     (IMBL_POINTS[i + 1][1], IMBL_POINTS[i + 1][0])])
         for i in range(len(IMBL_POINTS) - 1)]


def point_flags(lat, lon):
    """(on_sl_side, inside_danger_buffer, dist_km) for one fix."""
    p = Point(lon, lat)
    dists = [seg.distance(p) for seg in _SEGS]
    idx = int(np.argmin(dists))
    d_km = dists[idx] * 111.32
    A, B = IMBL_POINTS[idx], IMBL_POINTS[idx + 1]
    cross = (B[1] - A[1]) * (lat - A[0]) - (B[0] - A[0]) * (lon - A[1])
    return cross > 0, d_km < DANGER_DIST_KM, d_km


def true_zone(lat, lon):
    sl, buf, d = point_flags(lat, lon)
    if sl or buf:
        return "DANGER"
    if d < CAUTION_DIST_KM:
        return "CAUTION"
    return "SAFE"


# --------------------------------------------------------------------------- #
# Deployment-path helpers (un-batched, mirror app.py; used by the latency bench)
# --------------------------------------------------------------------------- #
def forecast_path(forecaster, recent_path, horizon):
    path = list(recent_path)
    projected = []
    for _ in range(horizon):
        nxt = forecaster.predict_next(path[-(LSTM_LOOKBACK + 1):])
        nxt = list(nxt.tolist() if hasattr(nxt, "tolist") else nxt)
        projected.append(nxt)
        path.append(nxt)
    return projected


def any_projected_in_danger(projected, predicate="buffer"):
    for pt in projected:
        sl, buf, _ = point_flags(pt[0], pt[1])
        if sl or (predicate == "buffer" and buf):
            return True
    return False


# --------------------------------------------------------------------------- #
# Trip sets (generated once, shared across policies / horizons / predicates)
# --------------------------------------------------------------------------- #
def first_cross_tick(traj):
    for i, s in enumerate(traj):
        if is_sri_lankan_side([s["lat"], s["lon"]], IMBL_POINTS):
            return i
    return None


def make_trip_sets():
    random.seed(SEED_FORCED)
    np.random.seed(SEED_FORCED)
    forced, tries = [], 0
    while len(forced) < N_FORCED and tries < N_FORCED * 20:
        tries += 1
        traj = generate_trajectory(trip_id=1_000_000 + tries, n_points=TRIP_LEN, mode="forced")
        tc = first_cross_tick(traj)
        if tc is not None:
            forced.append((traj[: tc + POST_CROSS_TICKS + 1], tc))
    forced_tries = tries

    random.seed(SEED_NEAR)
    np.random.seed(SEED_NEAR)
    near, near_calls = [], 0
    for i in range(N_NEAR):
        traj, attempts = generate_near_miss_trajectory(trip_id=2_000_000 + i, n_points=NEAR_LEN)
        near_calls += attempts
        if traj is not None:
            near.append(traj)

    print(f"  forced trips: {len(forced)} kept from {forced_tries} generated")
    print(f"  near-miss trips: {len(near)} kept, {near_calls} generator calls "
          f"(acceptance {len(near) / max(near_calls, 1):.2f})")
    return forced, near, {"forced_generated": forced_tries,
                          "near_miss_generator_calls": near_calls}


# --------------------------------------------------------------------------- #
# Batched rollouts -> per-tick, per-step (sl_side, in_buffer) flags
# --------------------------------------------------------------------------- #
def rollout_batch(name, forecaster, hist, H):
    """hist: (B, L+1, 2) absolute positions -> (B, H, 2) projected positions."""
    hist = np.array(hist, dtype=np.float64)
    B = hist.shape[0]
    out = np.zeros((B, H, 2))
    for h in range(H):
        window = hist[:, -(LSTM_LOOKBACK + 1):, :]
        if name == "LSTM":
            nxt = np.asarray(forecaster.predict_next_batch(window), dtype=np.float64)
        else:
            nxt = np.array([forecaster.predict_next(window[i].tolist()) for i in range(B)],
                           dtype=np.float64)
        out[:, h, :] = nxt
        hist = np.concatenate([hist, nxt[:, None, :]], axis=1)
    return out


def rollout_flags(name, forecaster, trajs):
    """
    For every trip k and tick t with a full lookback window, roll H_MAX steps and
    record sl[k][t] and buf[k][t] as length-H_MAX boolean lists (None before the
    window fills).  Lockstep across trips so the LSTM runs one batch per step.
    """
    coords = [np.array([[s["lat"], s["lon"]] for s in tr], dtype=np.float64) for tr in trajs]
    sl = [[None] * len(c) for c in coords]
    buf = [[None] * len(c) for c in coords]
    T = max(len(c) for c in coords)
    for t in range(LSTM_LOOKBACK + 1, T):
        active = [k for k, c in enumerate(coords) if t < len(c)]
        if not active:
            break
        hist = np.stack([coords[k][t - LSTM_LOOKBACK: t + 1] for k in active])
        proj = rollout_batch(name, forecaster, hist, H_MAX)
        for i, k in enumerate(active):
            flags = [point_flags(p[0], p[1]) for p in proj[i]]
            sl[k][t] = [f[0] for f in flags]
            buf[k][t] = [f[1] for f in flags]
    return sl, buf


def first_alert_from_flags(sl_k, buf_k, H, predicate):
    for t, s in enumerate(sl_k):
        if s is None:
            continue
        fire = any(s[:H]) or (predicate == "buffer" and any(buf_k[t][:H]))
        if fire:
            return t
    return None


def reactive_first_alert(traj):
    for i, s in enumerate(traj):
        if true_zone(s["lat"], s["lon"]) == "DANGER":
            return i
    return None


def run_horizon_sweep(forecasters, forced, near):
    awt_rows, far_rows = [], []

    # Reactive: H- and predicate-independent (fires on the DANGER zone rule).
    for k, (traj, tc) in enumerate(forced):
        tw = reactive_first_alert(traj)
        awt_rows.append({"policy": "Reactive", "predicate": "zone", "H": None, "trip": k,
                         "t_cross": tc, "t_warn": tw, "awt": (tc - tw) if tw is not None else None})
    for k, traj in enumerate(near):
        tw = reactive_first_alert(traj)
        far_rows.append({"policy": "Reactive", "predicate": "zone", "H": None, "trip": k,
                         "d_min_km": min(s["distance_to_imbl"] for s in traj),
                         "first_false_alert_tick": tw, "false_alert": tw is not None})

    for name in PREDICTIVE:
        f = forecasters[name]
        t0 = time.perf_counter()
        print(f"  {name:<9} rolling out forced...", end="", flush=True)
        sl_f, buf_f = rollout_flags(name, f, [tr for tr, _ in forced])
        print(" near-miss...", end="", flush=True)
        sl_n, buf_n = rollout_flags(name, f, near)
        print(f" done ({time.perf_counter() - t0:.0f}s)")
        for predicate in PREDICATES:
            for H in HORIZONS:
                for k, (traj, tc) in enumerate(forced):
                    tw = first_alert_from_flags(sl_f[k], buf_f[k], H, predicate)
                    awt_rows.append({"policy": name, "predicate": predicate, "H": H, "trip": k,
                                     "t_cross": tc, "t_warn": tw,
                                     "awt": (tc - tw) if tw is not None else None})
                for k, traj in enumerate(near):
                    tw = first_alert_from_flags(sl_n[k], buf_n[k], H, predicate)
                    far_rows.append({"policy": name, "predicate": predicate, "H": H, "trip": k,
                                     "d_min_km": min(s["distance_to_imbl"] for s in traj),
                                     "first_false_alert_tick": tw, "false_alert": tw is not None})
    return pd.DataFrame(awt_rows), pd.DataFrame(far_rows)


def summarise_sweep(awt_df, far_df):
    def awt_stats(sub):
        warned = sub[sub["awt"].notna() & (sub["awt"] > 0)]
        v = warned["awt"].astype(float).values
        return {
            "trips": int(len(sub)),
            "trips_with_advance_warning": int(len(warned)),
            "advance_warning_rate": float(len(warned) / len(sub)) if len(sub) else 0.0,
            "awt_mean": float(np.mean(v)) if len(v) else 0.0,
            "awt_median": float(np.median(v)) if len(v) else 0.0,
            "awt_p25": float(np.percentile(v, 25)) if len(v) else 0.0,
            "awt_p75": float(np.percentile(v, 75)) if len(v) else 0.0,
            "awt_std": float(np.std(v, ddof=1)) if len(v) > 1 else 0.0,
        }

    def far_stats(sub):
        fa = sub["false_alert"].astype(bool)
        ticks = sub.loc[fa, "first_false_alert_tick"].astype(float)
        return {
            "trips": int(len(sub)),
            "trips_with_false_alert": int(fa.sum()),
            "false_alert_rate": float(fa.mean()) if len(sub) else 0.0,
            "median_first_false_alert_tick": float(ticks.median()) if len(ticks) else None,
            "d_min_km_mean": float(sub["d_min_km"].mean()) if len(sub) else None,
            "d_min_km_min": float(sub["d_min_km"].min()) if len(sub) else None,
        }

    react_awt = awt_stats(awt_df[awt_df["policy"] == "Reactive"])
    react_far = far_stats(far_df[far_df["policy"] == "Reactive"])

    by_pred = {}
    for predicate in PREDICATES:
        by_pred[predicate] = {}
        for H in HORIZONS:
            by_pred[predicate][str(H)] = {}
            for name in PREDICTIVE:
                a = awt_stats(awt_df[(awt_df["policy"] == name) & (awt_df["H"] == H)
                                     & (awt_df["predicate"] == predicate)])
                fr = far_stats(far_df[(far_df["policy"] == name) & (far_df["H"] == H)
                                      & (far_df["predicate"] == predicate)])
                # eq. (1): buffer predicate inherits the reactive policy's residual
                # advance (it fires on buffer entry); crossing predicate should
                # warn ~H ticks before the crossing if the rollout were exact.
                predicted = H + react_awt["awt_mean"] if predicate == "buffer" else float(H)
                by_pred[predicate][str(H)][name] = {
                    "awt": a, "false_alert": fr,
                    "eq1_predicted_awt_mean": float(predicted),
                    "eq1_residual_ticks": float(a["awt_mean"] - predicted),
                }
    return {"reactive": {"awt": react_awt, "false_alert": react_far},
            "by_predicate": by_pred}


# --------------------------------------------------------------------------- #
# Zone classifier
# --------------------------------------------------------------------------- #
def _cls_metrics(y_true, y_pred, labels):
    p, r, f1, _ = precision_recall_fscore_support(y_true, y_pred, labels=labels, zero_division=0)
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "confusion_matrix": {"labels": labels,
                             "matrix": confusion_matrix(y_true, y_pred, labels=labels).tolist()},
        "per_class": {labels[i]: {"precision": float(p[i]), "recall": float(r[i]),
                                  "f1": float(f1[i])} for i in range(len(labels))},
    }


def eval_classifier_on_uniform(zone_model, n=20_000, seed=999):
    df = build_classifier_training_set(random_state=seed).sample(n=n, random_state=seed)
    y_pred = zone_model.model.predict(zone_model.scaler.transform(df[["lat", "lon"]]))
    labels = sorted(df["zone"].unique())
    out = {"n": int(len(df))}
    out.update(_cls_metrics(df["zone"], y_pred, labels))
    return out


def eval_classifier_on_trajectories(zone_model, df):
    X_scaled = zone_model.scaler.transform(df[["lat", "lon"]])
    y_pred = zone_model.model.predict(X_scaled)
    labels = sorted(df["zone"].unique())
    out = {"n": int(len(df)),
           "note": "classifier was trained on a uniform grid, so every trajectory fix is out-of-sample"}
    out.update(_cls_metrics(df["zone"], y_pred, labels))
    try:
        y_prob = zone_model.model.predict_proba(X_scaled)
        out["roc_auc_ovr"] = float(roc_auc_score(df["zone"], y_prob, multi_class="ovr",
                                                 labels=zone_model.model.classes_))
    except Exception as e:  # pragma: no cover
        out["roc_auc_ovr"] = None
        out["roc_auc_error"] = str(e)
    return out


# --------------------------------------------------------------------------- #
# One-step forecast error (held-out split only)
# --------------------------------------------------------------------------- #
def eval_forecaster_trajectory(forecaster, df):
    y_true, y_pred = [], []
    for trip_id in df["trip_id"].unique():
        coords = df[df["trip_id"] == trip_id][["lat", "lon"]].values
        if len(coords) < LSTM_LOOKBACK + 2:
            continue
        for i in range(LSTM_LOOKBACK, len(coords) - 1):
            pred = forecaster.predict_next(coords[i - LSTM_LOOKBACK: i + 1].tolist())
            y_pred.append(list(pred.tolist() if hasattr(pred, "tolist") else pred))
            y_true.append(coords[i + 1].tolist())
    y_true, y_pred = np.array(y_true, dtype=float), np.array(y_pred, dtype=float)
    dists = np.sqrt(np.sum((y_true - y_pred) ** 2, axis=1))
    mse = float(mean_squared_error(y_true, y_pred))
    return {
        "n_samples": int(len(y_true)),
        "mse_deg2": mse,
        "mae_deg": float(mean_absolute_error(y_true, y_pred)),
        "rmse_deg": float(np.sqrt(mse)),
        "ade_deg": float(np.mean(dists)),
        "fde_deg": float(dists[-1]) if len(dists) else 0.0,
        "ade_m_approx": float(np.mean(dists)) * 111_320,
        "rmse_m_approx": float(np.sqrt(mse)) * 111_320,
    }


# --------------------------------------------------------------------------- #
# Latency (deployment path: single vessel, un-batched, as app.py runs it)
# --------------------------------------------------------------------------- #
def bench_latency(zone_model, lstm, H=FORECAST_HORIZON, n_ticks=LATENCY_TICKS):
    random.seed(4242)
    np.random.seed(4242)
    trips = [generate_trajectory(trip_id=9_000_000 + i, n_points=TRIP_LEN, mode="forced")
             for i in range(n_ticks // TRIP_LEN + 2)]
    warm, samples, full_step = 10, [], []
    for traj in trips:
        path = []
        for step in traj:
            lat, lon = step["lat"], step["lon"]
            t0 = time.perf_counter()
            zone_model.predict(lat, lon)
            path.append([lat, lon])
            is_full = len(path) > LSTM_LOOKBACK + 1
            if is_full:
                lstm.predict_next(path[-(LSTM_LOOKBACK + 1):])
                any_projected_in_danger(forecast_path(lstm, path, H), "buffer")
            ms = (time.perf_counter() - t0) * 1000.0
            samples.append(ms)
            if is_full:
                full_step.append(ms)
            if len(samples) >= n_ticks + warm:
                break
        if len(samples) >= n_ticks + warm:
            break
    s = np.array(samples[warm:])
    f = np.array(full_step[warm:])
    return {
        "ticks": int(len(s)), "horizon": int(H),
        "all_ticks": {"mean_ms": float(s.mean()), "median_ms": float(np.median(s)),
                      "p95_ms": float(np.percentile(s, 95)), "p99_ms": float(np.percentile(s, 99))},
        "full_alerting_step": {"n": int(len(f)), "mean_ms": float(f.mean()),
                               "median_ms": float(np.median(f)),
                               "p95_ms": float(np.percentile(f, 95)),
                               "p99_ms": float(np.percentile(f, 99))},
        "note": "single-vessel deployment path (zone predict + 1-step + H-step un-batched "
                "rollout + buffer predicate); 'full_alerting_step' excludes the first "
                "lookback ticks where only the zone classifier runs. Measure with the "
                "machine otherwise idle.",
    }


# --------------------------------------------------------------------------- #
def main():
    os.makedirs("results", exist_ok=True)
    t_start = time.perf_counter()
    load_real_seed_data()

    zone_model = ZoneClassifier()
    zone_model.load()
    lstm = TrajectoryForecaster()
    lstm.load()
    forecasters = {"LSTM": lstm, "ConstVel": ConstantVelocityForecaster(),
                   "Kalman": KalmanForecaster(), "Reactive": ReactiveGeofence()}

    df_all = pd.read_csv("data/vessel_data.csv")
    if "split" in df_all.columns:
        df_test = df_all[df_all["split"] == "test"]
        split_note = "held-out trips (split == 'test' in data/vessel_data.csv)"
    else:
        df_test = df_all
        split_note = ("WARNING: no 'split' column found; scored on all trips "
                      "(in-sample). Re-run python -m src.train_model.")
    print(f"One-step forecast evaluation set: {split_note}; "
          f"{df_test['trip_id'].nunique()} trips, {len(df_test)} fixes")

    print("\n== Zone classifier ==")
    zone_uniform = eval_classifier_on_uniform(zone_model)
    zone_traj = eval_classifier_on_trajectories(zone_model, df_all)
    print(f"  uniform grid acc {zone_uniform['accuracy']:.4f} | "
          f"trajectories acc {zone_traj['accuracy']:.4f}")

    print("\n== One-step forecast error (held-out) ==")
    one_step = {}
    for name in PREDICTIVE:
        one_step[name] = eval_forecaster_trajectory(forecasters[name], df_test)
        print(f"  {name:<9} ADE {one_step[name]['ade_m_approx']:.1f} m  "
              f"RMSE {one_step[name]['rmse_m_approx']:.1f} m  (n={one_step[name]['n_samples']})")

    print("\n== Generating shared trip sets ==")
    forced, near, gen_info = make_trip_sets()

    print("\n== Horizon sweep (AWT on forced, false-alert rate on near-miss) ==")
    awt_df, far_df = run_horizon_sweep(forecasters, forced, near)
    awt_df.to_csv("results/awt.csv", index=False)
    far_df.to_csv("results/far_sweep.csv", index=False)
    sweep = summarise_sweep(awt_df, far_df)

    print("\n== Latency (machine should be otherwise idle) ==")
    latency = bench_latency(zone_model, lstm)
    fs = latency["full_alerting_step"]
    print(f"  full alerting step: mean {fs['mean_ms']:.1f} ms  median {fs['median_ms']:.1f} ms  "
          f"p99 {fs['p99_ms']:.1f} ms  (n={fs['n']})")

    n_params = int(lstm.model.count_params())

    summary = {
        "config": {
            "n_forced_trips": N_FORCED, "n_near_miss_trips": N_NEAR,
            "trip_len_forced": TRIP_LEN, "trip_len_near_miss": NEAR_LEN,
            "post_cross_ticks": POST_CROSS_TICKS,
            "horizons": HORIZONS, "predicates": PREDICATES,
            "default_forecast_horizon": FORECAST_HORIZON, "lstm_lookback": LSTM_LOOKBACK,
            "danger_km": DANGER_DIST_KM, "caution_km": CAUTION_DIST_KM,
            "seeds": {"forced": SEED_FORCED, "near_miss": SEED_NEAR},
            "trip_generation": gen_info,
            "one_step_eval_set": split_note,
            "one_step_eval_trips": int(df_test["trip_id"].nunique()),
            "wall_clock_s": float(time.perf_counter() - t_start),
        },
        "model": {"lstm_trainable_params": n_params},
        "zone_classifier_uniform": zone_uniform,
        "zone_classifier_trajectories": zone_traj,
        "trajectory_1step_heldout": one_step,
        "horizon_sweep": sweep,
        "latency": latency,
    }
    with open("results/summary.json", "w") as fh:
        json.dump(summary, fh, indent=2)

    print("\n== Sweep summary ==")
    r = sweep["reactive"]
    print(f"  Reactive (zone rule): AWT mean {r['awt']['awt_mean']:.2f}, "
          f"FAR {r['false_alert']['false_alert_rate']:.2f}")
    for predicate in PREDICATES:
        print(f"  -- predicate: {predicate}")
        for H in HORIZONS:
            for name in PREDICTIVE:
                s = sweep["by_predicate"][predicate][str(H)][name]
                print(f"     H={H:>2} {name:<9} AWT mean {s['awt']['awt_mean']:5.2f} "
                      f"(median {s['awt']['awt_median']:4.1f}, warned {s['awt']['trips_with_advance_warning']:2d}/50)  "
                      f"FAR {s['false_alert']['false_alert_rate']:.2f}  eq1 resid {s['eq1_residual_ticks']:+.2f}")
    print(f"\n  LSTM params: {n_params}   total wall-clock {summary['config']['wall_clock_s']:.0f}s")
    print("Wrote results/summary.json, results/awt.csv, results/far_sweep.csv")


if __name__ == "__main__":
    main()
