"""
End-to-end evaluation of the alerting pipeline.

Experiments (all regenerated by `python -m src.evaluate`):

  1. Zone classifier  - accuracy / per-class P-R-F1 on (a) a held-out uniform
                        sample of the region and (b) the synthetic trajectory set.
  2. One-step forecast - MAE / RMSE / ADE for LSTM, ConstVel, Kalman, scored
                        ONLY on trips with split == 'test' in data/vessel_data.csv.
  3. Horizon sweep    - for H in HORIZONS, each alerting policy, each alert
                        predicate, and each of SEEDS independent trip sets:
                          * Advance Warning Time on N_FORCED forced-crossing trips
                          * False-alert rate on N_NEAR near-miss trips that never
                            enter the DANGER zone (so any Danger alert is false)
                        Policies:
                          LSTM / ConstVel / Kalman - recursive rollout of a
                                     one-step forecaster, H steps
                          Analytic - zero-parameter time-to-line: smoothed
                                     velocity over the last L deltas, closing
                                     speed against the nearest segment's normal,
                                     fire when the straight-line time to the
                                     line (or buffer edge) is <= H.  No rollout.
                          Reactive - fires on the DANGER zone rule (H-independent)
                        Predicates:
                          'buffer'   - fire if a projected fix is on the SL side
                                       OR inside the 2 km DANGER buffer (shipped)
                          'crossing' - fire only on a projected SL-side fix
                        Reports pooled statistics over all seeds with 1,000-
                        resample bootstrap 95% CIs, the per-seed means, eq. (1)
                        residuals, and false-alert rate binned by each trip's
                        closest approach to the line.
  4. Latency          - per-tick wall-clock for the full single-vessel alerting
                        step (zone predict + 1-step + H-step rollout + predicate),
                        using the same un-batched call path as app.py.
  5. Model size       - trainable parameter count of the LSTM.

Outputs:
    results/awt.csv         one row per (seed, policy, predicate, H, forced trip)
    results/far_sweep.csv   one row per (seed, policy, predicate, H, near-miss trip)
    results/summary.json    everything the paper cites
"""

import json
import os
import random
import time

import numpy as np
import pandas as pd
from shapely.geometry import LineString, Point
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    precision_recall_fscore_support,
    roc_auc_score,
)

from src.baselines import (
    ConstantVelocityForecaster,
    KalmanForecaster,
    ReactiveGeofence,
)
from src.config import (
    CAUTION_DIST_KM,
    DANGER_DIST_KM,
    FORECAST_HORIZON,
    IMBL_POINTS,
    LSTM_LOOKBACK,
)
from src.data_generator import (
    generate_near_miss_trajectory,
    generate_trajectory,
    load_real_seed_data,
)
from src.geometry import distance_from_polyline, is_sri_lankan_side
from src.models import TrajectoryForecaster, ZoneClassifier
from src.train_model import build_classifier_training_set


N_FORCED = 50            # forced-crossing trips per seed (AWT)
N_NEAR = 50              # near-miss trips per seed (false-alert rate)
TRIP_LEN = 150           # ticks per forced trip
NEAR_LEN = 220           # ticks per near-miss trip (approach + trawl + return to port)
HORIZONS = [5, 10, 15, 20]
H_MAX = max(HORIZONS)
PREDICATES = ["buffer", "crossing"]
POST_CROSS_TICKS = 5     # forced trips are cut this many ticks after crossing
SEEDS = [(20260811, 20260812), (20260901, 20260902), (20260903, 20260904)]
APPROACH_BINS = [(0.0, 2.5), (2.5, 3.5), (3.5, 99.0)]   # closest approach, km
N_BOOT = 1000
BOOT_SEED = 7
LATENCY_TICKS = 1000

ROLLOUT = ["LSTM", "ConstVel", "Kalman"]
POLICIES = ROLLOUT + ["Analytic"]

KM_PER_DEG = 111.32


# --------------------------------------------------------------------------- #
# Geometry (cached segments; same maths as src/geometry.py)
# --------------------------------------------------------------------------- #
_SEGS = [LineString([(IMBL_POINTS[i][1], IMBL_POINTS[i][0]),
                     (IMBL_POINTS[i + 1][1], IMBL_POINTS[i + 1][0])])
         for i in range(len(IMBL_POINTS) - 1)]
# Unit normal of each segment pointing to the Sri Lankan side, in (lon, lat).
_NORMALS = []
for i in range(len(IMBL_POINTS) - 1):
    A, B = IMBL_POINTS[i], IMBL_POINTS[i + 1]
    dx, dy = B[1] - A[1], B[0] - A[0]           # (lon, lat) direction
    n = np.array([-dy, dx]) / np.hypot(dx, dy)  # cross(dir, n) > 0 => SL side
    _NORMALS.append(n)


def nearest_segment(lat, lon):
    p = Point(lon, lat)
    dists = [seg.distance(p) for seg in _SEGS]
    idx = int(np.argmin(dists))
    return idx, dists[idx]                       # degrees


def point_flags(lat, lon):
    """(on_sl_side, inside_danger_buffer, dist_km) for one fix."""
    idx, d_deg = nearest_segment(lat, lon)
    d_km = d_deg * KM_PER_DEG
    A, B = IMBL_POINTS[idx], IMBL_POINTS[idx + 1]
    cross = (B[1] - A[1]) * (lat - A[0]) - (B[0] - A[0]) * (lon - A[1])
    return cross > 0, d_km < DANGER_DIST_KM, d_km


def true_zone(lat, lon):
    sl, buf, d = point_flags(lat, lon)
    if sl or buf:
        return "DANGER"
    if d < CAUTION_DIST_KM:
        return "CAUTION"
    return "SAFE"


# --------------------------------------------------------------------------- #
# Deployment-path helpers (un-batched, mirror app.py; used by the latency bench)
# --------------------------------------------------------------------------- #
def forecast_path(forecaster, recent_path, horizon):
    path = list(recent_path)
    projected = []
    for _ in range(horizon):
        nxt = forecaster.predict_next(path[-(LSTM_LOOKBACK + 1):])
        nxt = list(nxt.tolist() if hasattr(nxt, "tolist") else nxt)
        projected.append(nxt)
        path.append(nxt)
    return projected


def any_projected_in_danger(projected, predicate="buffer"):
    for pt in projected:
        sl, buf, _ = point_flags(pt[0], pt[1])
        if sl or (predicate == "buffer" and buf):
            return True
    return False


# --------------------------------------------------------------------------- #
# Trip sets (generated once per seed, shared across policies / horizons / predicates)
# --------------------------------------------------------------------------- #
def first_cross_tick(traj):
    for i, s in enumerate(traj):
        if is_sri_lankan_side([s["lat"], s["lon"]], IMBL_POINTS):
            return i
    return None


def make_trip_sets(seed_forced, seed_near):
    random.seed(seed_forced)
    np.random.seed(seed_forced)
    forced, tries = [], 0
    while len(forced) < N_FORCED and tries < N_FORCED * 20:
        tries += 1
        traj = generate_trajectory(trip_id=1_000_000 + tries, n_points=TRIP_LEN, mode="forced")
        tc = first_cross_tick(traj)
        if tc is not None:
            forced.append((traj[: tc + POST_CROSS_TICKS + 1], tc))
    forced_tries = tries

    random.seed(seed_near)
    np.random.seed(seed_near)
    near, near_calls = [], 0
    for i in range(N_NEAR):
        traj, attempts = generate_near_miss_trajectory(trip_id=2_000_000 + i, n_points=NEAR_LEN)
        near_calls += attempts
        if traj is not None:
            near.append(traj)

    print(f"  seed {seed_forced}/{seed_near}: forced {len(forced)}/{forced_tries} crossed, "
          f"near-miss {len(near)} kept from {near_calls} draws")
    return forced, near, {"forced_generated": forced_tries, "near_miss_generator_calls": near_calls}


# --------------------------------------------------------------------------- #
# Rollout policies: batched rollouts -> per-tick, per-step (sl, buf) flags
# --------------------------------------------------------------------------- #
def rollout_batch(name, forecaster, hist, H):
    hist = np.array(hist, dtype=np.float64)
    B = hist.shape[0]
    out = np.zeros((B, H, 2))
    for h in range(H):
        window = hist[:, -(LSTM_LOOKBACK + 1):, :]
        if name == "LSTM":
            nxt = np.asarray(forecaster.predict_next_batch(window), dtype=np.float64)
        else:
            nxt = np.array([forecaster.predict_next(window[i].tolist()) for i in range(B)],
                           dtype=np.float64)
        out[:, h, :] = nxt
        hist = np.concatenate([hist, nxt[:, None, :]], axis=1)
    return out


def rollout_flags(name, forecaster, trajs):
    coords = [np.array([[s["lat"], s["lon"]] for s in tr], dtype=np.float64) for tr in trajs]
    sl = [[None] * len(c) for c in coords]
    buf = [[None] * len(c) for c in coords]
    T = max(len(c) for c in coords)
    for t in range(LSTM_LOOKBACK + 1, T):
        active = [k for k, c in enumerate(coords) if t < len(c)]
        if not active:
            break
        hist = np.stack([coords[k][t - LSTM_LOOKBACK: t + 1] for k in active])
        proj = rollout_batch(name, forecaster, hist, H_MAX)
        for i, k in enumerate(active):
            flags = [point_flags(p[0], p[1]) for p in proj[i]]
            sl[k][t] = [f[0] for f in flags]
            buf[k][t] = [f[1] for f in flags]
    return sl, buf


def first_alert_from_flags(sl_k, buf_k, H, predicate):
    for t, s in enumerate(sl_k):
        if s is None:
            continue
        if any(s[:H]) or (predicate == "buffer" and any(buf_k[t][:H])):
            return t
    return None


# --------------------------------------------------------------------------- #
# Analytic time-to-line policy (zero parameters, no rollout)
# --------------------------------------------------------------------------- #
def analytic_time_to_line(traj):
    """
    Per tick: signed distance to the nearest segment (deg, >0 on the Indian
    side, <0 on the SL side), and closing speed (deg/tick) of the velocity
    smoothed over the last LSTM_LOOKBACK deltas, along that segment's SL-facing
    normal.  None before the window fills (same eligibility as the rollouts).
    """
    coords = np.array([[s["lat"], s["lon"]] for s in traj], dtype=np.float64)
    out = [None] * len(coords)
    for t in range(LSTM_LOOKBACK + 1, len(coords)):
        v = np.mean(np.diff(coords[t - LSTM_LOOKBACK: t + 1], axis=0), axis=0)   # (dlat, dlon)
        lat, lon = coords[t]
        idx, d_deg = nearest_segment(lat, lon)
        n = _NORMALS[idx]                                   # (lon, lat)
        closing = v[1] * n[0] + v[0] * n[1]                 # deg/tick toward SL side
        sl, _, _ = point_flags(lat, lon)
        out[t] = (-d_deg if sl else d_deg, closing)
    return out


def analytic_first_alert(ttl, H, predicate):
    edge = DANGER_DIST_KM / KM_PER_DEG if predicate == "buffer" else 0.0
    for t, x in enumerate(ttl):
        if x is None:
            continue
        d_signed, closing = x
        if d_signed <= edge:                 # already across / already inside the buffer
            return t
        if closing > 0 and (d_signed - edge) / closing <= H:
            return t
    return None


def reactive_first_alert(traj):
    for i, s in enumerate(traj):
        if true_zone(s["lat"], s["lon"]) == "DANGER":
            return i
    return None


# --------------------------------------------------------------------------- #
# Sweep
# --------------------------------------------------------------------------- #
def run_horizon_sweep(forecasters, forced, near, seed_tag):
    awt_rows, far_rows = [], []
    d_min = [min(s["distance_to_imbl"] for s in tr) for tr in near]

    def add_awt(policy, predicate, H, k, tc, tw):
        awt_rows.append({"seed": seed_tag, "policy": policy, "predicate": predicate, "H": H,
                         "trip": k, "t_cross": tc, "t_warn": tw,
                         "awt": (tc - tw) if tw is not None else None})

    def add_far(policy, predicate, H, k, tw):
        far_rows.append({"seed": seed_tag, "policy": policy, "predicate": predicate, "H": H,
                         "trip": k, "d_min_km": d_min[k], "first_false_alert_tick": tw,
                         "false_alert": tw is not None})

    for k, (traj, tc) in enumerate(forced):
        add_awt("Reactive", "zone", None, k, tc, reactive_first_alert(traj))
    for k, traj in enumerate(near):
        add_far("Reactive", "zone", None, k, reactive_first_alert(traj))

    ttl_f = [analytic_time_to_line(tr) for tr, _ in forced]
    ttl_n = [analytic_time_to_line(tr) for tr in near]
    for predicate in PREDICATES:
        for H in HORIZONS:
            for k, (traj, tc) in enumerate(forced):
                add_awt("Analytic", predicate, H, k, tc, analytic_first_alert(ttl_f[k], H, predicate))
            for k, traj in enumerate(near):
                add_far("Analytic", predicate, H, k, analytic_first_alert(ttl_n[k], H, predicate))

    for name in ROLLOUT:
        f = forecasters[name]
        t0 = time.perf_counter()
        print(f"    {name:<9} rolling out...", end="", flush=True)
        sl_f, buf_f = rollout_flags(name, f, [tr for tr, _ in forced])
        sl_n, buf_n = rollout_flags(name, f, near)
        print(f" done ({time.perf_counter() - t0:.0f}s)")
        for predicate in PREDICATES:
            for H in HORIZONS:
                for k, (traj, tc) in enumerate(forced):
                    add_awt(name, predicate, H, k, tc, first_alert_from_flags(sl_f[k], buf_f[k], H, predicate))
                for k, traj in enumerate(near):
                    add_far(name, predicate, H, k, first_alert_from_flags(sl_n[k], buf_n[k], H, predicate))
    return pd.DataFrame(awt_rows), pd.DataFrame(far_rows)


# --------------------------------------------------------------------------- #
# Summaries with bootstrap CIs
# --------------------------------------------------------------------------- #
def _boot_ci(values, stat, rng, n_boot=N_BOOT):
    v = np.asarray(values, dtype=float)
    if len(v) == 0:
        return [None, None]
    idx = rng.integers(0, len(v), size=(n_boot, len(v)))
    boots = stat(v[idx], axis=1)
    return [float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))]


def awt_stats(sub, rng):
    warned = sub[sub["awt"].notna() & (sub["awt"] > 0)]
    v = warned["awt"].astype(float).values
    per_seed = sub.groupby("seed")["awt"].mean()
    return {
        "trips": int(len(sub)),
        "trips_with_advance_warning": int(len(warned)),
        "advance_warning_rate": float(len(warned) / len(sub)) if len(sub) else 0.0,
        "awt_mean": float(np.mean(v)) if len(v) else 0.0,
        "awt_mean_ci95": _boot_ci(v, np.mean, rng),
        "awt_median": float(np.median(v)) if len(v) else 0.0,
        "awt_p25": float(np.percentile(v, 25)) if len(v) else 0.0,
        "awt_p75": float(np.percentile(v, 75)) if len(v) else 0.0,
        "awt_std": float(np.std(v, ddof=1)) if len(v) > 1 else 0.0,
        "per_seed_mean": {str(s): float(m) for s, m in per_seed.items()},
        "across_seed_std": float(per_seed.std(ddof=1)) if len(per_seed) > 1 else 0.0,
    }


def far_stats(sub, rng):
    fa = sub["false_alert"].astype(bool).values.astype(float)
    per_seed = sub.groupby("seed")["false_alert"].mean()
    ticks = sub.loc[sub["false_alert"].astype(bool), "first_false_alert_tick"].astype(float)
    by_bin = {}
    for lo, hi in APPROACH_BINS:
        m = (sub["d_min_km"] >= lo) & (sub["d_min_km"] < hi)
        by_bin[f"{lo:g}-{hi:g}"] = {
            "n": int(m.sum()),
            "false_alert_rate": float(sub.loc[m, "false_alert"].astype(bool).mean()) if m.any() else None,
        }
    return {
        "trips": int(len(sub)),
        "trips_with_false_alert": int(fa.sum()),
        "false_alert_rate": float(fa.mean()) if len(sub) else 0.0,
        "false_alert_rate_ci95": _boot_ci(fa, np.mean, rng),
        "median_first_false_alert_tick": float(ticks.median()) if len(ticks) else None,
        "per_seed_rate": {str(s): float(r) for s, r in per_seed.items()},
        "across_seed_std": float(per_seed.std(ddof=1)) if len(per_seed) > 1 else 0.0,
        "by_closest_approach_km": by_bin,
    }


def summarise_sweep(awt_df, far_df):
    rng = np.random.default_rng(BOOT_SEED)
    react_awt = awt_stats(awt_df[awt_df["policy"] == "Reactive"], rng)
    react_far = far_stats(far_df[far_df["policy"] == "Reactive"], rng)
    near_all = far_df[far_df["policy"] == "Reactive"]
    approach = {
        "d_min_km_mean": float(near_all["d_min_km"].mean()),
        "d_min_km_min": float(near_all["d_min_km"].min()),
        "d_min_km_max": float(near_all["d_min_km"].max()),
        "n_by_bin": {f"{lo:g}-{hi:g}": int(((near_all["d_min_km"] >= lo) & (near_all["d_min_km"] < hi)).sum())
                     for lo, hi in APPROACH_BINS},
    }
    by_pred = {}
    for predicate in PREDICATES:
        by_pred[predicate] = {}
        for H in HORIZONS:
            by_pred[predicate][str(H)] = {}
            for name in POLICIES:
                a = awt_stats(awt_df[(awt_df["policy"] == name) & (awt_df["H"] == H)
                                     & (awt_df["predicate"] == predicate)], rng)
                fr = far_stats(far_df[(far_df["policy"] == name) & (far_df["H"] == H)
                                      & (far_df["predicate"] == predicate)], rng)
                predicted = H + react_awt["awt_mean"] if predicate == "buffer" else float(H)
                by_pred[predicate][str(H)][name] = {
                    "awt": a, "false_alert": fr,
                    "eq1_predicted_awt_mean": float(predicted),
                    "eq1_residual_ticks": float(a["awt_mean"] - predicted),
                }
    return {"reactive": {"awt": react_awt, "false_alert": react_far},
            "near_miss_closest_approach": approach,
            "by_predicate": by_pred}


# --------------------------------------------------------------------------- #
# Zone classifier
# --------------------------------------------------------------------------- #
def _cls_metrics(y_true, y_pred, labels):
    p, r, f1, _ = precision_recall_fscore_support(y_true, y_pred, labels=labels, zero_division=0)
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "confusion_matrix": {"labels": labels,
                             "matrix": confusion_matrix(y_true, y_pred, labels=labels).tolist()},
        "per_class": {labels[i]: {"precision": float(p[i]), "recall": float(r[i]),
                                  "f1": float(f1[i])} for i in range(len(labels))},
    }


def eval_classifier_on_uniform(zone_model, n=20_000, seed=999):
    df = build_classifier_training_set(random_state=seed).sample(n=n, random_state=seed)
    y_pred = zone_model.model.predict(zone_model.scaler.transform(df[["lat", "lon"]]))
    labels = sorted(df["zone"].unique())
    out = {"n": int(len(df))}
    out.update(_cls_metrics(df["zone"], y_pred, labels))
    return out


def eval_classifier_on_trajectories(zone_model, df):
    X_scaled = zone_model.scaler.transform(df[["lat", "lon"]])
    y_pred = zone_model.model.predict(X_scaled)
    labels = sorted(df["zone"].unique())
    out = {"n": int(len(df)),
           "note": "classifier was trained on a uniform grid, so every trajectory fix is out-of-sample"}
    out.update(_cls_metrics(df["zone"], y_pred, labels))
    try:
        y_prob = zone_model.model.predict_proba(X_scaled)
        out["roc_auc_ovr"] = float(roc_auc_score(df["zone"], y_prob, multi_class="ovr",
                                                 labels=zone_model.model.classes_))
    except Exception as e:  # pragma: no cover
        out["roc_auc_ovr"] = None
        out["roc_auc_error"] = str(e)
    return out


# --------------------------------------------------------------------------- #
# One-step forecast error (held-out split only)
# --------------------------------------------------------------------------- #
def eval_forecaster_trajectory(forecaster, df):
    y_true, y_pred = [], []
    for trip_id in df["trip_id"].unique():
        coords = df[df["trip_id"] == trip_id][["lat", "lon"]].values
        if len(coords) < LSTM_LOOKBACK + 2:
            continue
        for i in range(LSTM_LOOKBACK, len(coords) - 1):
            pred = forecaster.predict_next(coords[i - LSTM_LOOKBACK: i + 1].tolist())
            y_pred.append(list(pred.tolist() if hasattr(pred, "tolist") else pred))
            y_true.append(coords[i + 1].tolist())
    y_true, y_pred = np.array(y_true, dtype=float), np.array(y_pred, dtype=float)
    dists = np.sqrt(np.sum((y_true - y_pred) ** 2, axis=1))
    mse = float(mean_squared_error(y_true, y_pred))
    rng = np.random.default_rng(BOOT_SEED)
    return {
        "n_samples": int(len(y_true)),
        "mse_deg2": mse,
        "mae_deg": float(mean_absolute_error(y_true, y_pred)),
        "rmse_deg": float(np.sqrt(mse)),
        "ade_deg": float(np.mean(dists)),
        "ade_deg_ci95": _boot_ci(dists, np.mean, rng),
        "fde_deg": float(dists[-1]) if len(dists) else 0.0,
        "ade_m_approx": float(np.mean(dists)) * KM_PER_DEG * 1000,
        "ade_m_ci95": [c * KM_PER_DEG * 1000 for c in _boot_ci(dists, np.mean, rng)],
        "rmse_m_approx": float(np.sqrt(mse)) * KM_PER_DEG * 1000,
    }


# --------------------------------------------------------------------------- #
# Latency (deployment path: single vessel, un-batched, as app.py runs it)
# --------------------------------------------------------------------------- #
def bench_latency(zone_model, lstm, H=FORECAST_HORIZON, n_ticks=LATENCY_TICKS):
    random.seed(4242)
    np.random.seed(4242)
    trips = [generate_trajectory(trip_id=9_000_000 + i, n_points=TRIP_LEN, mode="forced")
             for i in range(n_ticks // TRIP_LEN + 2)]
    warm, samples, full_step = 10, [], []
    for traj in trips:
        path = []
        for step in traj:
            lat, lon = step["lat"], step["lon"]
            t0 = time.perf_counter()
            zone_model.predict(lat, lon)
            path.append([lat, lon])
            is_full = len(path) > LSTM_LOOKBACK + 1
            if is_full:
                lstm.predict_next(path[-(LSTM_LOOKBACK + 1):])
                any_projected_in_danger(forecast_path(lstm, path, H), "buffer")
            ms = (time.perf_counter() - t0) * 1000.0
            samples.append(ms)
            if is_full:
                full_step.append(ms)
            if len(samples) >= n_ticks + warm:
                break
        if len(samples) >= n_ticks + warm:
            break
    s = np.array(samples[warm:])
    f = np.array(full_step[warm:])
    return {
        "ticks": int(len(s)), "horizon": int(H),
        "all_ticks": {"mean_ms": float(s.mean()), "median_ms": float(np.median(s)),
                      "p95_ms": float(np.percentile(s, 95)), "p99_ms": float(np.percentile(s, 99))},
        "full_alerting_step": {"n": int(len(f)), "mean_ms": float(f.mean()),
                               "median_ms": float(np.median(f)),
                               "p95_ms": float(np.percentile(f, 95)),
                               "p99_ms": float(np.percentile(f, 99))},
        "note": "single-vessel deployment path (zone predict + 1-step + H-step un-batched "
                "rollout + buffer predicate); 'full_alerting_step' excludes the first "
                "lookback ticks where only the zone classifier runs. Measure with the "
                "machine otherwise idle.",
    }


# --------------------------------------------------------------------------- #
def main():
    os.makedirs("results", exist_ok=True)
    t_start = time.perf_counter()
    load_real_seed_data()

    zone_model = ZoneClassifier()
    zone_model.load()
    lstm = TrajectoryForecaster()
    lstm.load()
    forecasters = {"LSTM": lstm, "ConstVel": ConstantVelocityForecaster(),
                   "Kalman": KalmanForecaster(), "Reactive": ReactiveGeofence()}

    df_all = pd.read_csv("data/vessel_data.csv")
    if "split" in df_all.columns:
        df_test = df_all[df_all["split"] == "test"]
        split_note = "held-out trips (split == 'test' in data/vessel_data.csv)"
    else:
        df_test = df_all
        split_note = ("WARNING: no 'split' column found; scored on all trips "
                      "(in-sample). Re-run python -m src.train_model.")
    print(f"One-step forecast evaluation set: {split_note}; "
          f"{df_test['trip_id'].nunique()} trips, {len(df_test)} fixes")

    print("\n== Zone classifier ==")
    zone_uniform = eval_classifier_on_uniform(zone_model)
    zone_traj = eval_classifier_on_trajectories(zone_model, df_all)
    print(f"  uniform grid acc {zone_uniform['accuracy']:.4f} | trajectories acc {zone_traj['accuracy']:.4f}")

    print("\n== One-step forecast error (held-out) ==")
    one_step = {}
    for name in ROLLOUT:
        one_step[name] = eval_forecaster_trajectory(forecasters[name], df_test)
        lo, hi = one_step[name]["ade_m_ci95"]
        print(f"  {name:<9} ADE {one_step[name]['ade_m_approx']:.1f} m [{lo:.1f}, {hi:.1f}]  "
              f"RMSE {one_step[name]['rmse_m_approx']:.1f} m  (n={one_step[name]['n_samples']})")

    print("\n== Horizon sweep over seeds ==")
    awt_parts, far_parts, gen_info = [], [], {}
    for si, (sf, sn) in enumerate(SEEDS):
        forced, near, info = make_trip_sets(sf, sn)
        gen_info[f"seed{si}"] = {"forced": sf, "near_miss": sn, **info}
        a, f = run_horizon_sweep(forecasters, forced, near, seed_tag=si)
        awt_parts.append(a)
        far_parts.append(f)
    awt_df = pd.concat(awt_parts, ignore_index=True)
    far_df = pd.concat(far_parts, ignore_index=True)
    awt_df.to_csv("results/awt.csv", index=False)
    far_df.to_csv("results/far_sweep.csv", index=False)
    sweep = summarise_sweep(awt_df, far_df)

    print("\n== Latency (machine should be otherwise idle) ==")
    latency = bench_latency(zone_model, lstm)
    fs = latency["full_alerting_step"]
    print(f"  full alerting step: mean {fs['mean_ms']:.1f} ms  median {fs['median_ms']:.1f} ms  "
          f"p99 {fs['p99_ms']:.1f} ms  (n={fs['n']})")

    n_params = int(lstm.model.count_params())
    summary = {
        "config": {
            "n_forced_trips_per_seed": N_FORCED, "n_near_miss_trips_per_seed": N_NEAR,
            "n_seeds": len(SEEDS), "seeds": gen_info,
            "trip_len_forced": TRIP_LEN, "trip_len_near_miss": NEAR_LEN,
            "post_cross_ticks": POST_CROSS_TICKS,
            "horizons": HORIZONS, "predicates": PREDICATES, "policies": POLICIES,
            "approach_bins_km": APPROACH_BINS, "bootstrap_resamples": N_BOOT,
            "default_forecast_horizon": FORECAST_HORIZON, "lstm_lookback": LSTM_LOOKBACK,
            "danger_km": DANGER_DIST_KM, "caution_km": CAUTION_DIST_KM,
            "one_step_eval_set": split_note,
            "one_step_eval_trips": int(df_test["trip_id"].nunique()),
            "wall_clock_s": float(time.perf_counter() - t_start),
        },
        "model": {"lstm_trainable_params": n_params},
        "zone_classifier_uniform": zone_uniform,
        "zone_classifier_trajectories": zone_traj,
        "trajectory_1step_heldout": one_step,
        "horizon_sweep": sweep,
        "latency": latency,
    }
    with open("results/summary.json", "w") as fh:
        json.dump(summary, fh, indent=2)

    print("\n== Sweep summary (pooled over seeds; 95% bootstrap CI) ==")
    r = sweep["reactive"]
    ap = sweep["near_miss_closest_approach"]
    print(f"  near-miss closest approach: mean {ap['d_min_km_mean']:.2f} km, "
          f"range {ap['d_min_km_min']:.2f}-{ap['d_min_km_max']:.2f}, bins {ap['n_by_bin']}")
    print(f"  Reactive (zone rule): AWT mean {r['awt']['awt_mean']:.2f} "
          f"{r['awt']['awt_mean_ci95']}, FAR {r['false_alert']['false_alert_rate']:.2f}")
    for predicate in PREDICATES:
        print(f"  -- predicate: {predicate}")
        for H in HORIZONS:
            for name in POLICIES:
                s = sweep["by_predicate"][predicate][str(H)][name]
                a, fr = s["awt"], s["false_alert"]
                bins = "  ".join(f"{k}:{(v['false_alert_rate'] or 0)*100:3.0f}%" for k, v in fr["by_closest_approach_km"].items())
                print(f"     H={H:>2} {name:<9} AWT {a['awt_mean']:5.2f} [{a['awt_mean_ci95'][0]:.2f},{a['awt_mean_ci95'][1]:.2f}] "
                      f"seed-sd {a['across_seed_std']:.2f}  FAR {fr['false_alert_rate']*100:3.0f}% "
                      f"[{fr['false_alert_rate_ci95'][0]*100:.0f},{fr['false_alert_rate_ci95'][1]*100:.0f}]  "
                      f"eq1 {s['eq1_residual_ticks']:+.2f}  by-approach {bins}")
    print(f"\n  LSTM params: {n_params}   total wall-clock {summary['config']['wall_clock_s']:.0f}s")
    print("Wrote results/summary.json, results/awt.csv, results/far_sweep.csv")


if __name__ == "__main__":
    main()
